In [1]:
import numpy

In [2]:
import cv2

In [3]:
im_grey = cv2.imread("smallgrey.png", 0)

In [4]:
im_grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
im_grey[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [10]:
im_grey[:2,2:]

array([[104, 121, 143],
       [255, 255, 147]], dtype=uint8)

In [11]:
for i in im_grey:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [15]:
for i in im_grey.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [14]:
for i in im_grey.flat:
        print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [8]:
ims = numpy.hstack((im_grey, im_grey))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
ims = numpy.hstack((im_grey, im_grey, im_grey))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [11]:
ims = numpy.vstack((im_grey, im_grey))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
lst = numpy.hsplit(ims, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [14]:
lstv = numpy.vsplit(ims, 2)
lstv

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]